# Generated by Django 2.1.5 on 2023-03-06 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20230306_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 21, 41, 27, 410191, tzinfo=utc)),
        ),
    ]
