# Generated by Django 2.1.5 on 2023-03-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20230306_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='last_visit',
        ),
    ]
